---

- hosts: all
  become: true
  vars:
    username: joaquin

  tasks:

  - name: install python3 pip3 and open-jdk for Ubuntu
    apt:
      name: 
        - python3
        - python3-pip
        - default-jdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install python3 pip3 and open-jdk for CentOS
    yum:
      name:
        - python3
        - python3-pip
        - java-1.8.0-openjdk.x86_64
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: MOTD
    ansible.builtin.debug:
      msg: "Ansible Managed node by jvaldez19" 

  - name: Creating Users
    ansible.builtin.user:
      name: "{{ username }}"
      state: present
